config/routes.rb
Rails.application.routes.draw do

  # Home
  root to: 'home#vue'
  get 'react', to: 'home#react'
  get 'vue', to: 'home#vue'
  get 'about', to: 'home#about'
  get 'flash', to: 'home#flashtest'

  # Users
  get 'users/new'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  resources :users

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Lists & Tasks
  get 'tasks', to: 'tasks#all'
  resources :lists do
    resources :tasks, shallow: true
    get 'sharees', on: :member
  end

end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, -> { order(:priority, :updated_at)}
  has_many :owners, dependent: :destroy
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_list, only: [:show, :sharees, :edit, :update, :destroy]
  before_action :set_sharees, only: [:show, :sharees]

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
    puts @lists.inspect
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/1/sharees.json
  def sharees
    render plain: @sharees
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        @list.owners.create(user_id: current_user.id)
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    if @list.tasks.count > 0
      redirect_to list_url, alert: 'List contains Tasks that must be deleted before the List can be deleted.'
      return
    end
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_list
      @list = List.find(params[:id])
    end

    def set_sharees
      @sharees = @list.owners.select{|owner| owner.user != current_user}.map{|owner| owner.user.name}.join(', ')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :use_timeframe)
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
      <tr>
        <td><strong><%= form.label :name, "List Name" %></strong></td>
        <td><strong><%= form.label :use_timeframe, "Uses Trimeframes" %></strong></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong><%= form.text_field :name %></strong></td>
        <td><strong><%= form.check_box :use_timeframe %></strong></td>
        <td><%= form.submit %></td>
      </tr>
    </tbody>
  </table>

  <% if !@list.new_record? %>
    <%= link_to("Delete List", @list, method: :delete, class: "delete_button", confirm: 'Are you sure?') %>
  <% end %>

<% end %>

app/views/lists/_list.html.erb
<%= react_component("List", { list: list }) %>

<% if @sharees_per_list %>
  <% @sharees = @sharees_per_list[list.id] %>
<% end %>

<% if !@sharees.blank? %>
  (SHARED WITH: <%= @sharees %>)
<% end %>

<%= render list.tasks %>

<%= button_to 'New Task', new_list_task_path(list), options = { method: :get } %>

app/views/lists/_listJS.html.erb
<%= react_component("List", { list: list }) %>

<% if @sharees_per_list %>
  <% @sharees = @sharees_per_list[list.id] %>
<% end %>

<% if !@sharees.blank? %>
  (SHARED WITH: <%= @sharees %>)
<% end %>

<%= render list.tasks %>

<%= button_to 'New Task', new_list_task_path(list), options = { method: :get } %>

app/views/lists/edit.html.erb
<%= render 'form', list: @list %>

<h4><%= link_to '<< Back', @list %></h4>

app/views/lists/index.html.erb
<h1>Lists</h1>

<table>
  <% @lists.each do |list| %>
    <tr>
      <td><%= link_to list.name, list %></td>
      <td><%= list.use_timeframe ? 'Uses Timeframes' : '' %></td>
    </tr>
  <% end %>
</table>

<%= button_to 'New List', new_list_path, options = { method: :get } %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<h4><%= link_to '<< Back', root_path %></h4>

app/views/lists/show.html.erb
<%= render @list %>

<h4><%= link_to '<< Back', root_path %></h4>