config/routes.rb
Rails.application.routes.draw do

  # Home
  root to: 'home#vue'
  get 'react', to: 'home#react'
  get 'vue', to: 'home#vue'
  get 'about', to: 'home#about'
  get 'flash', to: 'home#flashtest'

  # Users
  get 'users/new'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  resources :users

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Lists & Tasks
  get 'tasks', to: 'tasks#all'
  resources :lists do
    resources :tasks, shallow: true
    get 'sharees', on: :member
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_list, only: [:index, :new, :create]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks/all
  # GET /tasks/all.json
  def all
    @tasks = Task.includes(:list).joins(:list).select("tasks.*, lists.name as listname").order("listname", :priority).all
  end

  # GET /lists/:list_id/tasks
  # GET /lists/:list_id/tasks.json
  def index
    @tasks = @list.tasks.order(:priority).all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    respond_to do |format|
      format.html { render }
      format.json { render json: @task }
    end
end

  # GET /lists/:list_id/tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @list = @task.list
  end

  # POST /lists/:list_id/tasks
  # POST /lists/:list_id/tasks.json
  def create
    @task = @list.tasks.create(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @list, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task.list, notice: 'Task was successfully updated.' }
        format.json { render json: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    list = @task.list
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:list_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :priority, :done)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, url: @task.new_record? ? [@list, @task] : @task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2><%= @list.name %></h2>

  <table>
    <thead>
      <tr>
        <td><strong><%= form.label :done %></strong></td>
        <td><strong><%= form.label :priority %></strong></td>
        <td><strong><%= form.label :name, "Task" %></strong></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= form.check_box :done %></td>
        <td><%= form.number_field :priority, options = { style: "width: 50px" } %></td>
        <td><%= form.text_field :name %></td>
        <td><%= form.submit %></td>
      </tr>
    </tbody>
  </table>

<% end %>

app/views/tasks/_task.html.erb
<tr <%= task.done? ? "class=completed" : "" %>>
  <% if local_assigns.has_key? :show_list_name %>
    <td><%= task.list.name %></td>
  <% end %>
  <td><input type="checkbox" <%= task.done? ? "checked" : "" %> onclick="myFunction()"></td>
  <td class="priority"><%= task.priority %></td>
  <td class="name"><%= task.name %></td>
  <td><%= button_to 'Edit', edit_task_path(task), options = { method: :get } %></td>
  <td><%= button_to 'X', task, options = { method: :delete, data: { confirm: 'Are you sure?' } } %></td>
</tr>

app/views/tasks/_taskJS.html..erb
<%= react_component("Task", { task: task }) %>

app/views/tasks/_taskJS.html.erb
<%= react_component("Task", { task: task }) %>

app/views/tasks/all.html.erb
<h2>All Tasks</h2>

<table>
  <%= render @tasks, show_list_name: true %>
</table>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

<h4><%= link_to '<< Back', list_path(@task.list) %></h4>

app/views/tasks/index.html.erb
<h1><%= @list.name %> Tasks</h1>

<table>
  <%= render @tasks %>
</table>

<%= button_to 'New Task', new_list_task_path, options = { method: :get } %>

app/views/tasks/new.html.erb
<%= render 'form', { task: @task, list: @list } %>

<h4><%= link_to '<< Back', list_path(@list) %></h4>

app/views/tasks/show.html.erb
<%= render @task %>

<h4><%= link_to '<< Back', list_path(@task.list) %></h4>