config/routes.rb
Rails.application.routes.draw do

  # Home
  root to: 'home#vue'
  get 'react', to: 'home#react'
  get 'vue', to: 'home#vue'
  get 'about', to: 'home#about'
  get 'flash', to: 'home#flashtest'

  # Users
  get 'users/new'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  resources :users

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Lists & Tasks
  get 'tasks', to: 'tasks#all'
  resources :lists do
    resources :tasks, shallow: true
    get 'sharees', on: :member
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by <a href="http://www.DevinDow.com/">Devin Dow</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">

  <div class="container">
    
    <div class="title_block">
      <%= link_to root_path do %>
        <%= image_tag('check.ico', size: '16', class: 'icon', alt: 'ToDo') %>
        <%= content_tag(:span, logged_in? ? current_user.name + "'s ToDos" : "ToDos", class: 'title') %>
      <% end %>
    </div>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>

  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('check.ico'), :rel => 'icon', :type =>  'image/x-icon' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |message_type, message| %>
        <% if message_type == 'notice' then message_type = 'success' end %>
        <% if message_type == 'alert' then message_type = 'danger' end %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <div class="container">
        <%= yield %>
      </div>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>

  </body>

</html>